### ISSUE TITLE
Enabling context-coloring-mode while region is narrowed throws an arg out of range error

### ISSUE THREAD

**Issue by aurelienbottazini** [jacksonrayhamilton/context-coloring#4]
Here is an example:

![jzeldktvnz](https://cloud.githubusercontent.com/assets/32635/20712076/eb8ab5ca-b642-11e6-931f-38d16948df75.gif)

GNU Emacs 25.1.1 (x86_64-apple-darwin16.0.0, NS appkit-1504.00 Version 10.12 (Build 16A323)) of 2016-10-17

Context coloring mode version
8.0.1

**Comment by jacksonrayhamilton** [comment]
Hi @aurelienbottazini, will you try #6 and see if it fixes the issue for you?

**Comment by jacksonrayhamilton** [comment]
Well, I just can't restrain my excitement to merge this. :smile: I hope it helps.
