### ISSUE TITLE
Clarification on what versions of JS are supported

### ISSUE THREAD

**Issue by aaronyo** [jacksonrayhamilton/context-coloring#7]
I'm currently making use of ES2017 and seeing a number of issues with context coloring. What versions of JavaScript are supported?

I'm happy to provide some examples of broken coloring if interested.

I've gotten a lot of use out of this module. Thank you!

**Comment by jacksonrayhamilton** [comment]
I originally wrote most of the code with ES5 in mind.  Some ES2015 and greater colorings may just work, others may require new code to be written.  The package always aims to support the latest official, published specification of ES (not drafts and not non-standard language extensions like JSX).

If you identify problems with coloring, I would appreciate if you opened an issue for each problem.  Thanks!

**Comment by jacksonrayhamilton** [comment]
Hi @aaronyo, checking in to see if you still thought there were issues with coloring.

**Comment by aaronyo** [comment]
For the moment, I've had to turn off context-coloring. If I remember correctly, I did so mainly because of problems introduced by JSX, which I understand you don't intend to support. (side note: I'm not sure how long I'll stick with JSX. Maybe someday I'll see how great it is, but for now whenever I say "JSX" it is usually followed by *grumble grumble*. I know there are some plain JS sugars over the react API, and I've written my own, but for now, I wanted to play with React in its most common and community-supported form...)

**Comment by jacksonrayhamilton** [comment]
Certainly.  Circularly, the problem you've encountered is that non-standard syntax extensions tend to throw existing linguistic tooling for a loop.  Hence why I don't want anything to do with it.  😄

It's pretty easy to use React without JSX.  I just assign `React.createElement` to a single-letter variable.

With JSX:

```jsx
class ExampleComponent extends React.Component {
  render () {
    return (
      <div className="example">
        <h1>Example Component</h1>
        <ul>
          <li>One item</li>
          <li>Another item</li>
        </ul>
      </div>
    );
  }
}
```

Plain JS:

```js
var r = React.createElement;
class ExampleComponent extends React.Component {
  render () {
    return (
      r('div', {className: 'example'},
        r('h1', {}, 'Example Component'),
        r('ul', {},
          r('li', {}, 'One item'),
          r('li', {}, 'Another item')))
    );
  }
}
```

If you use The One True Indent Style of 2 spaces, Emacs will coincidentally indent your elements properly.
